In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import TimeDistributed, Dense, LSTM, GRU, SimpleRNN

One to One

In [2]:
length = 10
seq = np.array([i /float(length) for i in range(length)])
X = seq.reshape(len(seq), 1, 1)
y = seq.reshape(len(seq), 1)
n_neuros = length
n_batch = length
n_epoch = 100

In [5]:
X

array([[[0. ]],

       [[0.1]],

       [[0.2]],

       [[0.3]],

       [[0.4]],

       [[0.5]],

       [[0.6]],

       [[0.7]],

       [[0.8]],

       [[0.9]]])

In [3]:
model = Sequential()
model.add(GRU(n_neuros, input_shape=(1, 1)))
model.add(Dense(1))

I0000 00:00:1783862013.512153   75409 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4168 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 6GB Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
/home/docroch/Projects/learning-data-science/.venv/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [4]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru (GRU)                       │ (None, 10)             │           390 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 401 (1.57 KB)

 Trainable params: 401 (1.57 KB)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.compile(loss='mean_absolute_error', optimizer='adam')

In [7]:
model.fit(X, y, epochs=n_epoch, batch_size=n_batch)

Epoch 1/100


I0000 00:00:1783862285.386756   77585 cuda_dnn.cc:461] Loaded cuDNN version 92400


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 935ms/step - loss: 0.5516
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.5479
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.5441
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.5404
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.5367
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.5330
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.5293
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.5257
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.5220
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.5183
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.5147
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.5110
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.5074
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.5037
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.5001
Epoch 16/100
1/1 ━━━━━━━━━━━━━

Many to One

In [8]:
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length)

In [9]:
X

array([[[0. ],
        [0.1],
        [0.2],
        [0.3],
        [0.4],
        [0.5],
        [0.6],
        [0.7],
        [0.8],
        [0.9]]])

In [10]:
y

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]])

In [15]:
model = Sequential()
model.add(GRU(n_neuros, input_shape=(length, 1)))
model.add(Dense(length))

In [16]:
model.compile(loss='mean_absolute_error', optimizer='adam')

In [17]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_2 (GRU)                     │ (None, 10)             │           390 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           110 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 500 (1.95 KB)

 Trainable params: 500 (1.95 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.fit(X, y, epochs=n_epoch, batch_size=n_batch)

Epoch 1/100


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 425ms/step - loss: 0.4916
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.4866
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.4815
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.4765
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.4714
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.4664
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.4612
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.4561
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.4509
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.4458
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.4405
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.4353
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.4300
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.4247
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.4194
Epoch 16/100
1/1 ━━━━━━━━━━━━━

In [19]:
model.predict(X, batch_size=n_batch)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[-0.00174632,  0.10405523,  0.1999463 ,  0.30102137,  0.40134192,
         0.49512112,  0.59417766,  0.4872483 ,  0.36285582,  0.12746212]],
      dtype=float32)

Many to Many

In [20]:
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length, 1)

In [21]:
X

array([[[0. ],
        [0.1],
        [0.2],
        [0.3],
        [0.4],
        [0.5],
        [0.6],
        [0.7],
        [0.8],
        [0.9]]])

In [22]:
y

array([[[0. ],
        [0.1],
        [0.2],
        [0.3],
        [0.4],
        [0.5],
        [0.6],
        [0.7],
        [0.8],
        [0.9]]])

In [23]:
model = Sequential()
model.add(GRU(n_neuros, input_shape=(length, 1), return_sequences=True))
model.add(TimeDistributed(Dense(length)))

/home/docroch/Projects/learning-data-science/.venv/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [24]:
model.compile(loss='mean_absolute_error', optimizer='adam')

In [25]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_3 (GRU)                     │ (None, 10, 10)         │           390 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed                │ (None, 10, 10)         │           110 │
│ (TimeDistributed)               │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 500 (1.95 KB)

 Trainable params: 500 (1.95 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.fit(X, y, epochs=n_epoch, batch_size=n_batch)

Epoch 1/100


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 600ms/step - loss: 0.4521
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.4492
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.4464
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.4435
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.4406
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.4378
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.4349
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.4321
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.4292
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.4263
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.4234
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.4205
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.4176
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.4147
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.4117
Epoch 16/100
1/1 ━━━━━━━━━━━━━

In [27]:
model.predict(X, batch_size=n_batch)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step


array([[[0.14325845, 0.1683774 , 0.09573374, 0.12117168, 0.16738889,
         0.16876587, 0.11418629, 0.13387215, 0.07372414, 0.11393946],
        [0.22122617, 0.21649387, 0.1876855 , 0.18112531, 0.25299293,
         0.20968857, 0.17453074, 0.1807723 , 0.14633931, 0.18858622],
        [0.3005259 , 0.24777044, 0.2847395 , 0.25541824, 0.3324644 ,
         0.23269472, 0.2476064 , 0.23033994, 0.23275101, 0.2674214 ],
        [0.37808168, 0.269177  , 0.38395444, 0.3377052 , 0.40787658,
         0.24611318, 0.32978395, 0.27860302, 0.32715926, 0.34931624],
        [0.45256495, 0.28507584, 0.48281416, 0.4233455 , 0.48057905,
         0.25459468, 0.41768298, 0.32339218, 0.42557636, 0.43332773],
        [0.522814  , 0.29804742, 0.5791162 , 0.5083758 , 0.551314  ,
         0.26067707, 0.5081759 , 0.36400655, 0.52477705, 0.5177467 ],
        [0.58746165, 0.3095013 , 0.67086536, 0.5892305 , 0.6202772 ,
         0.26574403, 0.5983675 , 0.40063292, 0.6218316 , 0.6001033 ],
        [0.64514846, 0.3200